package main

const configurationMdTemplate = `
This is generated by magicstring tool version  0.1.1

# Configurations

## Core configurations

| Item                  | Value           |
|-----------------------|-----------------|
|              Coin name| $CoinName
|            Coin symbol| $CoinSymbol
|    BlockchainPubkeyStr| $BlockchainPubkeyStr
|    BlockchainSeckeyStr| $BlockchainSeckeyStr
|      GenesisAddressStr| $GenesisAddressStr
|             PrivateKey| $gasPrivateKey
|                       | $gasSeed
|    GenesisSignatureStr| $GenesisSignatureStr
|       GenesisTimestamp| $GenesisTimestamp
|                       | $GenesisTimestampReadable
|      GenesisCoinVolume| $GenesisCoinVolume
|            PeerListURL| $PeerListURL
|                   Port| $Port
|       WebInterfacePort| $WebInterfacePort
|       RPCInterfacePort| $RPCInterfacePort
|            GenesisUxID| $GenesisUxID
|     GenesisUxSignature| $GenesisUxSignature
|                 Node 1| $node001
|                 Node 2| $node002
|                 Node 3| $node003
|                 Node 4| $node004
|                 Node 5| $node005

# Deploy nodes

scp -P 28001 $coinname-0.23.0-bin-linux-x64.tar.gz root@$node001:/root
scp -P 28001 $coinname-0.23.0-bin-linux-x64.tar.gz root@$node002:/root
scp -P 28001 $coinname-0.23.0-bin-linux-x64.tar.gz root@$node003:/root
scp -P 28001 $coinname-0.23.0-bin-linux-x64.tar.gz root@$node004:/root

# Start master node

./$coinname -master=true -master-secret-key=$BlockchainSeckeyStr  -launch-browser=false –download-peerlist=false

# Start normal node

./$coinname -launch-browser=false

# Distribution addresses

`

func configurationFile(fn string, c CoinConfigT) {
	configString := injectValues(configurationMdTemplate, c)
	configString = insertDistributionAddrs(configString, c)
	write2File(fn, configString)
}

func insertDistributionAddrs(text string, c CoinConfigT) string {
	for _, addr := range c.DistributionAddresses {
		text = text + addr
	}
	return text
}
